package com.lion.demo.provider.temp.model;

import java.io.Serializable;
import java.util.Date;

public class TempMybatis implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp_mybatis.id
     *
     * @mbg.generated Mon Apr 15 11:30:14 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp_mybatis.name
     *
     * @mbg.generated Mon Apr 15 11:30:14 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp_mybatis.type
     *
     * @mbg.generated Mon Apr 15 11:30:14 CST 2019
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp_mybatis.status
     *
     * @mbg.generated Mon Apr 15 11:30:14 CST 2019
     */
    private Boolean status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp_mybatis.create_time
     *
     * @mbg.generated Mon Apr 15 11:30:14 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp_mybatis.update_time
     *
     * @mbg.generated Mon Apr 15 11:30:14 CST 2019
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table temp_mybatis
     *
     * @mbg.generated Mon Apr 15 11:30:14 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp_mybatis.id
     *
     * @return the value of temp_mybatis.id
     *
     * @mbg.generated Mon Apr 15 11:30:14 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp_mybatis.id
     *
     * @param id the value for temp_mybatis.id
     *
     * @mbg.generated Mon Apr 15 11:30:14 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp_mybatis.name
     *
     * @return the value of temp_mybatis.name
     *
     * @mbg.generated Mon Apr 15 11:30:14 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp_mybatis.name
     *
     * @param name the value for temp_mybatis.name
     *
     * @mbg.generated Mon Apr 15 11:30:14 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp_mybatis.type
     *
     * @return the value of temp_mybatis.type
     *
     * @mbg.generated Mon Apr 15 11:30:14 CST 2019
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp_mybatis.type
     *
     * @param type the value for temp_mybatis.type
     *
     * @mbg.generated Mon Apr 15 11:30:14 CST 2019
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp_mybatis.status
     *
     * @return the value of temp_mybatis.status
     *
     * @mbg.generated Mon Apr 15 11:30:14 CST 2019
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp_mybatis.status
     *
     * @param status the value for temp_mybatis.status
     *
     * @mbg.generated Mon Apr 15 11:30:14 CST 2019
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp_mybatis.create_time
     *
     * @return the value of temp_mybatis.create_time
     *
     * @mbg.generated Mon Apr 15 11:30:14 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp_mybatis.create_time
     *
     * @param createTime the value for temp_mybatis.create_time
     *
     * @mbg.generated Mon Apr 15 11:30:14 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp_mybatis.update_time
     *
     * @return the value of temp_mybatis.update_time
     *
     * @mbg.generated Mon Apr 15 11:30:14 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp_mybatis.update_time
     *
     * @param updateTime the value for temp_mybatis.update_time
     *
     * @mbg.generated Mon Apr 15 11:30:14 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temp_mybatis
     *
     * @mbg.generated Mon Apr 15 11:30:14 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", type=").append(type);
        sb.append(", status=").append(status);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}