package com.lion.demo.provider.temp.mapper;

import com.lion.demo.provider.temp.model.TempMybatis;
import com.lion.demo.provider.temp.model.TempMybatisExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TempMybatisMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temp_mybatis
     *
     * @mbg.generated Mon Apr 15 11:30:14 CST 2019
     */
    long countByExample(TempMybatisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temp_mybatis
     *
     * @mbg.generated Mon Apr 15 11:30:14 CST 2019
     */
    int deleteByExample(TempMybatisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temp_mybatis
     *
     * @mbg.generated Mon Apr 15 11:30:14 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temp_mybatis
     *
     * @mbg.generated Mon Apr 15 11:30:14 CST 2019
     */
    int insert(TempMybatis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temp_mybatis
     *
     * @mbg.generated Mon Apr 15 11:30:14 CST 2019
     */
    int insertSelective(TempMybatis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temp_mybatis
     *
     * @mbg.generated Mon Apr 15 11:30:14 CST 2019
     */
    List<TempMybatis> selectByExample(TempMybatisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temp_mybatis
     *
     * @mbg.generated Mon Apr 15 11:30:14 CST 2019
     */
    TempMybatis selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temp_mybatis
     *
     * @mbg.generated Mon Apr 15 11:30:14 CST 2019
     */
    int updateByExampleSelective(@Param("record") TempMybatis record, @Param("example") TempMybatisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temp_mybatis
     *
     * @mbg.generated Mon Apr 15 11:30:14 CST 2019
     */
    int updateByExample(@Param("record") TempMybatis record, @Param("example") TempMybatisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temp_mybatis
     *
     * @mbg.generated Mon Apr 15 11:30:14 CST 2019
     */
    int updateByPrimaryKeySelective(TempMybatis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temp_mybatis
     *
     * @mbg.generated Mon Apr 15 11:30:14 CST 2019
     */
    int updateByPrimaryKey(TempMybatis record);
}